; PlatformIO Project Configuration File

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3